### ISSUE TITLE
Add sub project for the NodeJS server

### ISSUE THREAD

**Issue by Dudrie** [Dudrie/Tutor-Management-System#1]
# 🎯 Goal
Add a sub project which will include the NodeJS server implementation.

# ✔ ToDo
- [x] Move client to use yarn instead of npm
- [x] Add a NodeJS server in a sub folder
- [x] Configure yarn workspaces with the client and the server sub projects
- [x] Add docker-compose file to start container with a dev MongoDB database
  - [x] Start MongoDB
  - [x] Start admin interface for the MongoDB
