### ISSUE TITLE
Quality of life changes

### ISSUE THREAD

**Issue by Dudrie** [Dudrie/Tutor-Management-System#12]
# 🎯 Goal
This issue collects different issues raised during the usability test or prolonged internal tests which should be changed if possible. These points will be implemented through several seperat issues (referenced at the point if started) or - if rejected - there will be a reason why.

Items marked with a ❓ are ideas which are _not_ viewed as 'must' or 'should' have.

# 👩‍🎓 Student overview
- [x] ~~On student creation: Show lastnames of team members instead of team number.~~
  _The names of the members are already shown additionaly to the team number._
- [x] ~~Assign student to a team on creation automatically:~~ [#103]
  - ~~Fill teams until they are 'full'.~~
  - ~~If all teams are full (or there are no teams) than create a new one on creation of the student.~~
- [x] ~~After creation the schein status bar of that student is in 'pending' state.~~
- [x] ~~Editing a student does not update the email button on it's bar.~~
- [x] ~~After creation if the student did get assigned to a team the team dropdown box is not reflecting this.~~ [#103]
- [ ] ❓ Animate the newly created student.
- [ ] ❓ Make course of studies a dropdown box.

# 👥 Teams
- [x] ~~If team is empty the text on the bar should reflect that.~~ [#173]
- [x] ~~Team row does not get properly adjusted if it's team gets edited. [#172]~~
- [x] ~~Show members of a team as Chips?~~

# 🔢 Points
- [ ] On entering points: Highlight if points exceed maximum points of an exercise (ie because it has bonus points)
- [x] ~Make bonus points / exercises visually distinct from the regular points / exercises~ [#163].
- [x] ~Ability to add comments to every part of valuation (exercises)~ [#19].
- [x] ~More flexible way of distributing points (see sheets below)~ [#15].
- ~~'Save all' button on entering points & presentations.~~ (Not needed anymore due to the redesign of the view).
- [x] ~Show which student is part of which team~ [#15].
- [x] ~~If student changes the team and the points of set team are adjusted afterwards:~~
  - ~~Student's points get adjusted if they match the ones of the (old) team~~
  - ~~__OR__ Tutor gets a reminder of adjusting said student.~~
  - This is basically solved with the changes made for version 2.

# 📅 Attendance
- [x] ~~🍰 Cake flag and reminder of it~~ [#75].
- [x] ~~All students should be initially set to "present"~~ [#76].
- [ ] On small screens the buttons have a strange layout.
- [x] ~~Long notes destroy the table layout.~~

# 🚪 Login
- [ ] Improve user feedback on relogin dialog after session times out. This includes error messages aswell as a success message.
- [ ] The error message box on the change password form should have a margin on the bottom.
- [ ] LDAP connection.

# 👨‍🏫 Tutorial
- [x] ~~❓ _On tutorial creation the tutorial slot should automatically increase (if all previous entered slots are actual numbers)._~~
- [x] ~~On substitute editing: Highlight days with substitutes.~~ [#381]
- [x] ~~On creation the admin should be able to apply settings which will be respected [#256]. These include:~~
  - ~~Week count~~
  - ~~Holidays / Days off~~
  Closed by [#381]
- [x]  ~~Show correctors on bar aswell (maybe as Chips?)~~ [#48].

# 👩‍💼 User
- [x] ~~The tutorial dropdown on user creation should show if a tutorial is already assigned and to whom it is assigned.~~

# 📜 Sheets
- [ ] Ctrl + Enter should create a new exercise if an exercise row is focused.
- [ ] Exercises should be sortable (ie Drag & Drop).
- [x] ~Allow sub exercises to have a more detailed point distribution~ [#15].
- [x] ~If a new exercise is added the point field should be focused~ [#15].

# 📝 Scheinexam
- [ ] Move the date to be the secondary text instead of being displayed in parantheses behind the scheinexam number.

# 🖌 Drawer
- [x] ~~Make 'Management' section collapsable~~ _(Not needed anymore due to the new layout)_
- [x] ~~Adjust order of buttons to have the more used ones further up top.~~ [#34]
- [ ] Add tooltip to 'substitute' & 'corrector' icon.
- [x] ~~If the drawer is collabsed:~~
  - ~~The Y scrollbar lies above the items which partially hides them.~~
  - ~~There's an X scrollbar and the text of the items does not hide.~~

# 📑 Forms
- [x] ~Mark required field through the `required` property~ [Partially: #24, #78].
- [ ] If object is created the first field of the form should be focused (like the firstname of students).
  - [x] ~~Firstname of students.~~ [#103]
