### ISSUE TITLE
Add CI/CD to the repository

### ISSUE THREAD

**Issue by Dudrie** [Dudrie/Tutor-Management-System#4]
# 🎯 Goal
Add a CI/CD pipeline to the project.

# ✔ ToDos
- [x] Add configuration file and link with CircleCI
- [x] Add code quality job
- [x] Add compile job
- [x] Add test job

# 📒 Note
This will introduce build steps for the current Java server aswell. These steps will be removed in the future.
