### ISSUE TITLE
Change DB to SQL

### ISSUE THREAD

**Issue by Dudrie** [Dudrie/Tutor-Management-System#957]
## 🏁 Goal

Change the database used to a SQL database.

## ✔ ToDos

- [x] ~~Decide which SQL database to use (mysql vs postgres vs mariadb).~~
      ~~Postgres~~, MySQL
- [x] Add [Mikro-ORM](https://mikro-orm.io/docs/installation/) and the corresponding SQL dependency.
- [x] Add pre/post hooks
- [x] Add encryption to sensitive data
- [x] Add the `@mirko-orm/nestjs` package ([instructions here](https://mikro-orm.io/docs/usage-with-nestjs)) and properly initialized the `MikroOrmModule`.
- [x] Add entities for the database entities needed (those will replace the former mongoose documents).
- [x] ~~Introduce proper repositories.~~ Using injected repositories makes things more complicated, because the Mikro-ORM NestJS package can not autoload entities from a directory and make those entities' repositories injectable...
- [x] Adjust services to use the entities & repositories instead of the documents.
- [x] Adjust session to use the SQL database.
- [x] Rewrite tests to use an ~~in-memory~~ SQL database.
      In theory only the initialization and clean up of the tests should be affected (can those be simplified through some helpers additionally?).
- [x] Remove mongoose documents & all MongoDB related dependencies.
- [x] Adjust GitHub actions ~~if neccessary~~
    - [x] Adjust action for unit tests.  
    - [x] The docker-test workflow should need adjustments but those should be the same adjustments needed for the docker-compose file in the documentation.
- [x] Adjust documentation, especially the installation page.
- [ ] `findAll()` methods in all (?) services should not use `populate: true`
      This makes retrieving the entities from the DB really slow. Instead they should only populate the fields actually necessary for the part calling the `findAll()` method.
- [x] Re-add fixes from main since 2.3.5: [Compare changes](https://github.com/Dudrie/Tutor-Management-System/compare/issue-957-Change_DB_to_SQL...main)
- [ ] Test deployment version.

## 💡 Reason

The reason behind this is that the usage of a non-SQL database (like MongoDB) proofed to be not optimal for the use case at hand.
Especially later during a term the time it takes to read a student with all it's gradings from the DB increases significantly due to the way students & gradings are structured.
The structuring of the gradings (ie put them into the students) can not be changed due to the fact that multiple students can have the same grading.
SQL databases should provide a more consistent and faster solution for this task due to the ability to perform joins over multiple tables.
